export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    THEME: 'THEME',
    ACTIVE_PAGE: 'ACTIVE_PAGE',
    SOCKET: 'SOCKET',
    USERS: {
        SEARCH_USERS: 'SEARCH_USERS',
        GET_USER: 'GET_USER'
    },
    PROFILE: {
        LOADING: 'LOADING',
        GET_USER: 'GET_USER',
        GET_USER_POST: 'GET_USER_POST',
        RESET_USER_POSTS: 'RESET_USER_POSTS',
        SET_USER: 'SET_USER'
    },
    POST: {
        CREATE_POST: 'CREATE_POST',
        LOADING_POST: 'LOADING_POST',
        GET_POSTS: 'GET_POSTS',
        GET_NEW_POSTS: 'GET_NEW_POSTS',
        UPDATE_POST: 'UPDATE_POST',
        DELETE_POST: 'DELETE_POST'
    },
    STATUS: {
        OPEN_MODAL_HOME_POST: 'OPEN_MODAL_HOME_POST',
        HIDE_MODAL_HOME_POST: 'HIDE_MODAL_HOME_POST',
        OPEN_MODAL_DETAIL_POST: 'OPEN_MODAL_DETAIL_POST',
        HIDE_MODAL_DETAIL_POST: 'HIDE_MODAL_DETAIL_POST',
        CURRENT_EDIT_STATUS: 'CURRENT_EDIT_STATUS'
    },
    DETAILPOST: {
        GET_DETAILPOST: 'GET_ DETAILPOST'
    },
    DISCOVER: {
        GET_POSTS_DISCOVER: ' GET_POSTS_DISCOVER'
    },
    SUGGESTION: {
        LOADING: 'LOADING',
        SUGGEST_USER: 'SUGGER_USER'
    },
    NOTIFICATION: {
        GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
        CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
        UPDATE_NOTIFICATION: ' UPDATE_NOTIFICATION',
        DELETE_NOTIFICATION: 'DELETE_NOTIFICATION'
    }
};
