export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    THEME: 'THEME',
    ACTIVE_PAGE: 'ACTIVE_PAGE',
    USERS: {
        SEARCH_USERS: 'SEARCH_USERS',
        GET_USER: 'GET_USER'
    },
    PROFILE: {
        LOADING: 'LOADING',
        GET_USER: 'GET_USER',
        GET_USER_POST: 'GET_USER_POST',
        ADD_USER_POST: 'ADD_USER_POST',
        DELETE_USER_POST: 'DELETE_USER_POST',
        SET_USER: 'SET_USER'
    },
    POST: {
        CREATE_POST: 'CREATE_POST',
        LOADING_POST: 'LOADING_POST',
        GET_POST: 'GET_POST',
        UPDATE_POST: 'UPDATE_POST',
        DELETE_POST: 'DELETE_POST',
        LIKE_POST: 'LIKE_POST',
        UNLIKE_POST: 'UNLIKE_POST',
        CREATE_COMMENT: 'CREATE_COMMENT',
        DELETE_COMMENT: 'DELETE_COMMENT',
        UPDATE_COMMENT: 'UPDATE_COMMENT',
        LIKE_COMMENT: 'LIKE_COMMENT',
        UNLIKE_COMMENT: 'UNLIKE_COMMENT',
        CREATE_REPLY: 'CREATE_REPLY',
        UPDATE_REPLY: 'UPDATE_REPLY',
        LIKE_REPLY: 'LIKE_REPLY'
    },
    STATUS: {
        OPEN_MODAL: 'OPEN_MODAL',
        HIDE_MODAL: 'HIDE_MODAL',
        CURRENT_EDIT_STATUS: 'CURRENT_EDIT_STATUS'
    }
};
