export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    THEME: 'THEME',
    ACTIVE_PAGE: 'ACTIVE_PAGE',
    SOCKET: 'SOCKET',
    USERS: {
        SEARCH_USERS: 'SEARCH_USERS',
        SEARCH_LOADING: 'SEARCH_LOADING',
        GET_USER: 'GET_USER'
    },
    PASSWORD: {
        RESET: 'RESET',
        SEND_CODE: 'SEND_CODE',
        CONFIRM_CODE: 'CONFIRM_CODE'
    },
    PROFILE: {
        LOADING: 'LOADING',
        GET_USER: 'GET_USER',
        GET_USER_POST: 'GET_USER_POST',
        GET_USER_SAVED_POSTS: 'GET_USER_SAVED_POSTS',
        RESET_USER_POSTS: 'RESET_USER_POSTS',
        RESET_USER_SAVED_POSTS: 'RESET_USER_SAVED_POSTS',
        SET_USER: 'SET_USER'
    },
    POST: {
        CREATE_POST: 'CREATE_POST',
        LOADING_POST: 'LOADING_POST',
        GET_POSTS: 'GET_POSTS',
        GET_NEW_POSTS: 'GET_NEW_POSTS',
        UPDATE_POST: 'UPDATE_POST',
        DELETE_POST: 'DELETE_POST'
    },
    STATUS: {
        OPEN_MODAL_HOME_POST: 'OPEN_MODAL_HOME_POST',
        HIDE_MODAL_HOME_POST: 'HIDE_MODAL_HOME_POST',
        OPEN_MODAL_DETAIL_POST: 'OPEN_MODAL_DETAIL_POST',
        HIDE_MODAL_DETAIL_POST: 'HIDE_MODAL_DETAIL_POST',
        OPEN_MODAL_USER: 'OPEN_MODAL_USER',
        HIDE_MODAL_USER: 'HIDE_MODAL_USER',
        CURRENT_EDIT_STATUS: 'CURRENT_EDIT_STATUS'
    },
    DETAILPOST: {
        GET_DETAILPOST: 'GET_ DETAILPOST'
    },
    DISCOVER: {
        POSTS_DISCOVER_LOADING: 'POSTS_DISCOVER_LOADING',
        GET_POSTS_DISCOVER: ' GET_POSTS_DISCOVER'
    },
    SUGGESTION: {
        LOADING: 'LOADING',
        SUGGEST_USER: 'SUGGER_USER'
    },
    NOTIFICATION: {
        GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
        CREATE_NOTIFICATION: 'CREATE_NOTIFICATION',
        UPDATE_NOTIFICATION: ' UPDATE_NOTIFICATION',
        DELETE_NOTIFICATION: 'DELETE_NOTIFICATION'
    },
    MESSAGE: {
        GET_USER_ONLINE_LIST: 'GET_USER_ONLINE_LIST',
        GET_MESSAGES: 'GET_MESSAGES',
        ADD_MESSAGE: 'ADD_MESSAGE',
        LOAD_MORE_MESSAGE: 'LOAD_MORE_MESSAGE',
        UPDATE_MESSAGE: 'UPDATE_MESSAGE',
        UPDATE_READED_CONVERSATION: 'UPDATE_READED_CONVERSATION',
        SET_CURRENT_RECEIVER: 'SET_CURRENT_RECEIVER',
        GET_CONVERSATIONS: 'GET_CONVERSATIONS',
        SET_CURRENT_CONVERSATION: 'SET_CURRENT_CONVERSATION',
        MESSAGE_LOADING: 'MESSAGE_LOADING'
    },
    CALL: {
        CALL_USER: 'CALL_USER',
        CALLING: 'CALLING'
    },
    PEER: 'PEER',
    MARKETPLACE: {
        GET_PRODUCTS: 'GET_PRODUCTS',
        MARKETPLACE_LOADING: 'MARKETPLACE_LOADING',
        MARKETPLACE_RESET: 'MARKETPLACE_RESET',
        MARKETPLACE_SET_SEARCHED_KEYWORD: 'MARKETPLACE_SET_SEARCHED_KEYWORD',
        MARKETPLACE_SET_QUERY_LIST: 'MARKETPLACE_SET_QUERY_LIST'
    }
};
